Optimise dockerfiles (multi stage, caching)
hotosm/underpass pull request #444
Opened 2023-11-08 14:26 UTC by spwoodcock

Fixes #439

- Updated to multi-stage builds.
- Only installed required **runtime** libs for final underpass image.
- Reordered layers for more efficient caching.
- Added labels.

Significant image size reductions:
- api 1.31GB --> 228MB
- underpass 2.19GB --> 1.88GB
- ui 1.1GB --> 18.5MB

The underpass image could probably be reduced further by selective usage of boost libraries, instead of `libboost-all-dev`.

2023-11-08 18:52 UTC, emi420 reviewed
The build is working, but some things are failing or missing. 

-  The directory `/code` changed, and with this, the bootstrap script stopped working for Docker
- The API port changed, so the UI is not working now
- The source files and the utils folder is missing, so the bootstrap script is not available anymore

Keep in mind that the Docker image is not only for deployment, but also for running Underpass locally. Maybe we can have two different Docker images, one for deployment and one for development/testing/running locally.

2023-11-09 01:31 UTC, spwoodcock commented on docker-compose.yml
> +      - "8080:8080"
I can use 5000:8080 if you prefer?

The underlying tool used to serve changed.
Before you we bundling all node_modules, then runing `yarn cosmos` for the dev server.
The new dockerfile builds the dist, then serves via a webserver, which runs on port 8080.

2023-11-09 01:31 UTC, spwoodcock commented on docker/underpass-ui.dockerfile
> +LABEL org.hotosm.fmtm.app-name="underpass-ui" \
Thanks for the catch!

2023-11-09 01:56 UTC, spwoodcock commented on docker/underpass.dockerfile
> +WORKDIR /app
I prefer /opt as it's more standard linux, but I updated to /code to avoid changing the CI scripts.

2023-11-09 01:59 UTC, spwoodcock commented
The standard way to have different environments is to add different stages to the dockerfile.

I usually have a `debug` stage, and a `prod` stage. The target can be specified when you build (using docker compose, gh-workflows, etc).

2023-11-09 03:55 UTC, spwoodcock commented
Made updates: see in the first post.

Let me know if anything else needs updating 👍

2023-11-09 13:21 UTC, spwoodcock commented
Made the final update just now:
- Create `debug` images for local debug stage and `prod` stage for the actual releases.
- Bind mount local code into the containers so you get live updates for both fastapi and cosmos.

I can build and push the images to the hotosm container registry.
The only thing left to do @emi420 is to associate the packages with the repo (only the repo owner can do that):
https://github.com/orgs/hotosm/packages/container/package/underpass
https://github.com/orgs/hotosm/packages/container/package/underpass%2Fapi
https://github.com/orgs/hotosm/packages/container/package/underpass%2Fui
'Link this package to a repository'

2023-11-20 23:33 UTC, spwoodcock commented
I will rebase with `master` to solve conflicts.

2023-11-21 15:03 UTC, spwoodcock commented
Rebased - should be working.

I can't work out why the test is failing with a 403 unauthorised, when the permissions are set for the repo actions to write to the container/package repository.

I feel like it is because I am running the workflow & I don't have any member permissions on the repo.

2023-11-30 02:39 UTC, emi420 commented
It's mostly working! with `docker-compose up -d` the UI is not working but if I change the port is working perfectly:

```
ports:
      - "${UI_PORT:-5000}:5000"
```

CI is failing, possibly because the workflow version and GitHub settings, you know better what changes are needed there.

Thanks @spwoodcock

2023-11-30 02:40 UTC, emi420 requested changes
It's mostly working! with docker-compose up -d the UI is not working but if I change the port is working perfectly:

ports:
      - "${UI_PORT:-5000}:5000"

CI is failing, possibly because the workflow version and GitHub settings, you know better what changes are needed there.

Thanks @spwoodcock

2023-11-30 02:40 UTC, emi420 commented on docker-compose.yml
> +      - "${UI_PORT:-5000}:8080"
Hey @spwoodcock , I've tested this PR and the UI is working only when I change this to  ```- "${UI_PORT:-5000}:5000"```

2023-12-01 09:15 UTC, merged

2023-12-01 09:21 UTC, spwoodcock commented
That seemed to work 🎉